FROM node:22-alpine
WORKDIR /app
COPY package.json ./
RUN npm install
RUN npm install @mdi/font
RUN npm install @intlify/unplugin-vue-i18n vite-plugin-vuetify sass sass-loader -D
RUN npm install markdown-it
COPY . .
EXPOSE 4000
CMD ["npm", "run", "dev"]
